config/routes.rb
Guide::Application.routes.draw do

  mount RedactorRails::Engine => '/redactor_rails'

  root :to => 'home#index'

  get "/" => "home#index"

  get "/search" => "subjects#search"

  resources :subjects

  resources :notes

  post "notes/:id" => "notes#update"

  delete "notes/:id" => "notes#destroy"

  resources :search 

  get "/aboutus" => "aboutus#index"

end

app/models/note.rb
class Note < ActiveRecord::Base
  attr_accessible :id, :title, :content, :word_count, :searchable

  validates :title, :presence => {:message => "should not be blank"}
  validates :searchable, :presence => {:message => "should not be blank"}
  # validates :title, :presence => true, {:on => :save, :message => "should not be blank"
  # validates :searchable, :presence => {:on => :save, :message => "should not be blank"}

  has_and_belongs_to_many :subjects

  searchable :auto_index => true do 
    text :title
    text :searchable, :default_boost => 2
  end
end

app/models/redactor_rails/asset.rb
class RedactorRails::Asset < ActiveRecord::Base
  include RedactorRails::Orm::ActiveRecord::AssetBase
  delegate :url, :current_path, :size, :content_type, :filename, :to => :data
  validates_presence_of :data
end

app/models/redactor_rails/document.rb
class RedactorRails::Document < RedactorRails::Asset
  mount_uploader :data, RedactorRailsDocumentUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/redactor_rails/picture.rb
class RedactorRails::Picture < RedactorRails::Asset
  mount_uploader :data, RedactorRailsPictureUploader, :mount_on => :data_file_name

  def url_content
    url(:content)
  end
end

app/models/subject.rb
class Subject < ActiveRecord::Base
  attr_accessible :id, :title

  has_and_belongs_to_many :notes
end

app/controllers/aboutus_controller.rb
class AboutusController < ApplicationController

  def index
    
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index 
    
  end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

  def index
    @notes = Note.all
  end

  def show
    @note = Note.find(params[:id])
  end

  def new 
    @note = Note.new
  end

  def edit
    @note = Note.find(params[:id])
  end

  def create
    @note = Note.new(params[:note])
      if @note.update_attributes(:title => params[:title], :content => params[:notes][:content], :searchable => (params[:notes][:content]).gsub(%r{</?[^>]+?>}, ''))
        @note.save
        render :show
      else
        render :new
      end
  end

  def update 
    @note = Note.find(params[:id])
    if @note.update_attributes(:title => params[:title], :content => params[:notes][:content], :searchable => (params[:notes][:content]).gsub(%r{</?[^>]+?>}, ''))
      @note.save
      redirect_to note_path(@note.id)
    else
      render :show
    end
  end

  def destroy
    @note = Note.find(params[:id]).destroy
    redirect_to root_url
  end

  def search
    @search = Note.search(:include => [:subjects]) do 
      keywords(params[:q])
    end
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def search 
    page_size = 10

    @search = Note.search do 
      keywords params[:q]

      with :include_search, true
      paginate page: params[:page], per_page: page_size
    end

    @results = @search.results

    @total = @search.total
    @paging = @total > page_size
    @start = (@search.current_page - 1)* page_size + 1
    @end = [@start + page_size - 1, @total].min 

    render (if @results.empty? then :no_results else :results end)
  end

end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController

  def index
    @search = Note.search do
      fulltext params[:q]
    end
    
    @results = @search.results
  end

  def show
    @subject = Subject.find(params[:id])
  end

  def new 
    @subject = Subject.new
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def create
    @subject = Subject.new(params[:Subject])
      if @subject.save
        render :index, :notice => "Saved!"
      else
        render :new
      end
  end

  def update 
    @subject = Subject.find(params[:id])
  end

  def destroy
    @subject = Subject.find(params[:id]).destroy
    redirect_to :subject
  end

  def search 
    page_size = 10

    @search = Note.search do 
      keywords params[:q]

      with :include_search, true
      paginate page: params[:page], per_page: page_size
    end

    @results = @search.results

    @total = @search.total
    @paging = @total > page_size
    @start = (@search.current_page - 1)* page_size + 1
    @end = [@start + page_size - 1, @total].min 

    render (if @results.empty? then :no_results else :results end)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/aboutus/index.html.erb
<!doctype html>
<html>
<head>
<h1 class="makers">Meet your makers</h1>

<div class="bioimages">

<!-- Button to trigger modal -->
<a href="#myModal" role="button" class="" data-toggle="modal"><img class="bio-img" src="assets/ashley_beattie.jpg"/></a>
 
<!-- Modal -->
<div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Ashley Beattie</h3>
  </div>
  <div class="modal-body">
    <p>
      I'm a recent graduate of Bitmaker Labs' immersive "Introduction to Web Development Class."  Over the past 9 weeks I've learned quite a lot about Ruby, Ruby on Rails, Javascript, JQuery, CSS/SCSS, HTML/HAML...  and more!  When it comes to webdev, you name it, we've probably seen it!     
    </p>
    <p>
      The app you're taking a look at right now is a research-task-enabling notes application.  It was designed to facilitate the research aspects when one is developing web applications.  It currently employs Solr to index and search the vast knowledge bases that I've discovered over the course of my learning, as well as to organize research projects.  It also uses as lightweight JQuery WYSIWYG text-editor to showcase the work on the notes pages.
    </p>
    <p>
      Future improvements will be to index bookmarks, scrape websites, organize searches and visualize the knowledge bases using D3.js.
    </p>
    <p>
      Thanks for taking a look!
    </p>
    <script type="text/javascript">
      $(document).ready(function () {
        //$('#info_myself').hide();
        //$('#info_myself').fadeIn(2000);
        // define active class for 
        $('.bio-img').addClass('active');
        // 
        //
      });
    </script>
  </div>
</div>

<!-- Button to trigger modal -->
<a href="#myModal2" role="button" class="" data-toggle="modal"><img class="bio-img" src="assets/37.jpg"/></a>

<!-- Modal -->
<div id="myModal2" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3 id="myModalLabel">Nick Gray</h3>
  </div>
  <div class="modal-body">
    <p>
      I'm a recent graduate of Bitmaker Labs' immersive "Introduction to Web Development Class."  Over the past 9 weeks I've learned quite a lot about Ruby, Ruby on Rails, Javascript, JQuery, CSS/SCSS, HTML/HAML...  and more!  When it comes to webdev, you name it, we've probably seen it!
    </p>
    <p>
      The app you're taking a look at right now is a research-task-enabling notes application.  It was designed to facilitate the research aspects when one is developing web applications.  It currently employs Solr to index and search the vast knowledge bases that I've discovered over the course of my learning, as well as to organize research projects. It also uses as lightweight JQuery WYSIWYG text-editor to showcase the work on the notes pages.
    </p>
    <p>
      Future improvements will be to index bookmarks, scrape websites, organize searches and visualize the knowledge bases using D3.js.
    </p>
    <p>
      Thanks for taking a look!
    </p>
    <script type="text/javascript">
      $(document).ready(function () {
        //$('#info_myself').hide();
        //$('#info_myself').fadeIn(2000);
        // define active class for 
        $('.bio-img').addClass('active');
        // 
        //
      });
    </script>
  </div>
</div>

</div>

</body>
</html>

app/views/home/index.html.erb
<img src="notepad_background3-1_copy.gif" class="note-image">

<br>
<br>
<br>

<div class="search-box" textarea style="width:500px; height:375px;">
<%= form_tag subjects_path, :method => "get" do %>
  <p>
    <%= text_field_tag(:q, params[:q], :placeholder => "            Search all notes!") %>
    <%= submit_tag "Search", :class => "search btn"%>
  </p>
<br>
<input type="checkbox" name="<%= params[:q] %>" value="<%= params[:q] %>" class="googleSearch">Search Google for this <br><br>

<input type="checkbox" name="<%= params[:q] %>" value="<%= params[:q] %>" class="soSearch">Search StackOverflow for this <br>

<!-- <input type="checkbox" name="<%= params[:q] %>" value="<%= params[:q] %>" id="googleSearch"><br><br>
<label for="googleSearch"><span>Search Google for this</span></label>

<input type="checkbox" name="<%= params[:q] %>" value="<%= params[:q] %>" id="soSearch"><br>
<label for="soSearch"><span>Search StackOverflow for this</span></label>
 -->
<% end %>

</div>

<script>

$(".search.btn").click(function(){
  var q = $("#q").val();
  q = encodeURIComponent(q);

  if ($(".soSearch").is(":checked")) {
    window.open('http://stackoverflow.com/search?q=' + q);
  }
  if ($(".googleSearch").is(":checked")) {
    window.open('http://www.google.com/');
  }
})

</script>

app/views/layouts/_navigation.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <a class="research-header" href="/">Researcher</a>
    <ul class="nav">
      <li><a href="/notes" style="color:white;" class="nav-links">Notes</a></li>
      <li><a href="/aboutus" style="color:white;" class="nav-links">About Us</a></li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Researcher" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="spaann12">
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/note/show.html.erb
The notes page

app/views/notes/index.html.erb
<div class="btn new-note">
  <h4><%= link_to "Create New Note", :action => "new" %></h4>
</div>
<br>
<br>
<div class="total-notes">
<h2>All of your Notes:</h2>
<div class="all-notes">
<ul>
  <% @notes.each do |note| %>
  <li><span class="larger"><%= link_to note.title, note_path(note) %></span></li>
<% end %>
</ul>
</div>
</div>

app/views/notes/new.html.erb
<form accept-charset="UTF-8" action="/notes" method="post">
  <div style="margin:0;padding:0">
    <input name="utf8" type="hidden" value="&#x2713;" />
  </div>

  <% if @note.errors.any? %>
    <div class="errors">
      <h3>Please fix the following errors</h3>
      <ul>
        <% @note.errors.full_messages.each do |e| %>
          <li><%= e %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div id="redactor_content">
  <%= form_for @note, :url => { :action => "create"}, :html => { :class => "note_form"} do |f| %>
    </br><%= text_area_tag :title, @note.title, :class => "redactor_title", :rows => 1, :cols => 60 %></br>
    <%= text_area_tag :"notes[content]", @note.content, :class => "redactor", :rows => 200, :cols => 120 %>
    <%= f.submit "Create Note", :class => "btn" %>
  <% end %>
  </div>
</form>

app/views/notes/show.html.erb
<% if @note.errors.any? %>
  <div class="errors">
    <h3>Please fix the following errors</h3>
    <ul>
      <% @note.errors.full_messages.each do |e| %>
        <li><%= e %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<p>
  <%= button_to "Delete This Note", note_path(@note.id), :method => :delete, :class => "btn" %>
</p>

<form action="" method="post"> 
  <p>
    <input type="submit" class="btn" value="Save This Note"></input>
  </p>
  
  <div id="redactor_content">
    <%= text_area_tag :title, @note.title, :class => "redactor_title", :rows => 1, :cols => 60 %></br>
    <%= text_area_tag :"notes[content]", @note.content, :class => "redactor", :rows => 200, :cols => 150 %>
  </div>
</form>

app/views/subjects/index.html.erb
<div class="search-results">
  <h1>Results</h1>
  </br>
  <ul>
  <% @results.each do |result| %>
  <li class="search-notes"><%= link_to result.title, note_path(result) %></li>
  <% end %>
  </ul>
</div>

app/views/subjects/new.html.erb
<form accept-charset="UTF-8" action="/subjects" method="post">
  <div style="margin:0;padding:0">
    <input name="utf8" type="hidden" value="&#x2713;" />
  </div>
  <%= form_for @subject, :url => { :action => "create"}, :html => { :class => "subject_form"} do |f| %>
    <%= f.text_field :title %>
    <%= f.submit "Create" %>
  <% end %>
</form>